[package]
name = "libbitdemon"
version = "0.1.0"
edition = "2021"

[lib]
name = "bitdemon"

[dependencies]
aes.workspace = true
byteorder.workspace = true
cbc.workspace = true
chrono.workspace = true
des.workspace = true
hmac.workspace = true
log.workspace = true
num-derive.workspace = true
num-traits.workspace = true
rand.workspace = true
sha1.workspace = true
snafu.workspace = true
tiger.workspace = true
