[package]
name = "libbitdemon"
version = "0.1.0"
edition = "2021"

[lib]
name = "bitdemon"

[dependencies]
byteorder.workspace = true
log.workspace = true
num-derive.workspace = true
num-traits.workspace = true
snafu.workspace = true
