[workspace]
members = [
    "libbitdemon",
    "dw-server"
]
resolver = "1"

[workspace.dependencies]
chrono = "0.4.40"
log = "0.4.26"
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.9.0"
snafu = "0.8.5"
