[workspace]
members = [
    "libbitdemon",
    "dw-server"
]
resolver = "1"

[workspace.dependencies]
chrono = "0.4.41"
log = "0.4.27"
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.9.2"
snafu = "0.8.9"
