[package]
name = "auth-server"
version = "0.1.0"
edition = "2021"

[dependencies]
libbitdemon = { path = "../../libbitdemon" }
byteorder = "1.5.0"
env_logger = "0.11.6"
log = "0.4.25"
num-derive = "0.4.2"
num-traits = "0.2.19"
