[package]
name = "lobby-server"
version = "0.1.0"
edition = "2021"

[dependencies]
libbitdemon = { path = "../../libbitdemon" }

env_logger.workspace = true
log.workspace = true
num-derive.workspace = true
num-traits.workspace = true
snafu.workspace = true
